"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { motion, AnimatePresence } from "framer-motion";
import { Building2, Calendar, Users, KeyRound, CheckCircle2, AlertCircle, Loader2, Lock, GraduationCap, BadgeCheck, Sparkles, MapPin, ArrowRight, ShieldCheck } from "lucide-react";

interface Drive {
    id: string;
    company: string;
    drive_date: string;
    status: string;
    drive_code: string;
    expected_intake: number;
    enrolled_count: number;
    min_cgpa: number;
    min_10th: number;
    min_12th: number;
    max_backlogs: number;
    allowed_branches: string[];
    target_roles: string;
    location: string;
    source?: "" | "hr";
    job_id?: string;
}

export default function StudentDrivesPage() {
    const [drives, setDrives] = useState<Drive[]>([]);
    const [loading, setLoading] = useState(true);
    const [registeredIds, setRegisteredIds] = useState<string[]>([]);
    const [codeInputs, setCodeInputs] = useState<Record<string, string>>({});
    const [joinStatus, setJoinStatus] = useState<Record<string, { type: "success" | "error"; text: string }>>({});
    const [joining, setJoining] = useState<string | null>(null);
    const [studentProfile, setStudentProfile] = useState<any>(null);

    useEffect(() => {
        const init = async () => {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;

            // Fetch placement drives
            const { data: drivesData } = await supabase
                .from("placement_drives")
                .select("id, company, drive_date, status, drive_code, expected_intake, enrolled_count, min_cgpa, min_10th, min_12th, max_backlogs, allowed_branches, target_roles, location")
                .not("status", "eq", "Closed")
                .order("drive_date", { ascending: true });

            // Fetch HR/ job drives
            const { data: jobsData } = await supabase
                .from("jobs")
                .select("id, company_name, title, department, location, description, required_skills, min_score, created_at, job_code, min_10th, min_12th, max_backlogs, allowed_branches")
                .order("created_at", { ascending: false });

            // Normalize HR jobs into same Drive shape
            const hrDrives: Drive[] = (jobsData || []).map((j: any) => ({
                id: `hr_${j.id}`,
                company: j.company_name,
                drive_date: j.created_at,
                status: "Active",
                drive_code: j.job_code || "", // unique code generated by HR at creation
                expected_intake: 0,
                enrolled_count: 0,
                min_cgpa: j.min_score ? j.min_score / 10 : 0,
                min_10th: parseFloat(j.min_10th) || 0,
                min_12th: parseFloat(j.min_12th) || 0,
                max_backlogs: j.max_backlogs !== null && j.max_backlogs !== undefined ? parseInt(j.max_backlogs) : 99,
                allowed_branches: j.allowed_branches || [],
                target_roles: `${j.title} · ${j.department || ""}`,
                location: j.location || "",
                source: "hr" as const,
                job_id: j.id,
            }));

            const tpoDrives: Drive[] = (drivesData || []).map((d: any) => ({ ...d, source: "" as const }));

            // Fetch student's registrations for both drives and jobs
            const { data: regs } = await supabase
                .from("drive_registrations")
                .select("drive_id, job_id")
                .eq("student_id", user.id);

            // Fetch student profile for eligibility preview
            const { data: profile } = await supabase
                .from("profiles")
                .select("grad_cgpa, tenth_percent, twelfth_percent, active_backlogs, branch")
                .eq("id", user.id)
                .single();

            setDrives([...tpoDrives, ...hrDrives]);

            // Map drive_id and hr_job_id correctly
            const regIds = (regs || []).map((r: any) => r.drive_id ? r.drive_id : `hr_${r.job_id}`);
            setRegisteredIds(regIds);

            setStudentProfile(profile);
            setLoading(false);
        };
        init();
    }, []);

    const handleJoin = async (driveId: string, driveCode: string) => {
        const enteredCode = codeInputs[driveId]?.trim().toUpperCase();
        if (!enteredCode) {
            setJoinStatus(prev => ({ ...prev, [driveId]: { type: "error", text: "Please enter the access code." } }));
            return;
        }

        setJoining(driveId);
        setJoinStatus(prev => ({ ...prev, [driveId]: undefined! }));

        try {
            const res = await fetch("/api/drives/join", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ driveId, code: enteredCode }),
            });
            const data = await res.json();

            if (res.ok && data.success) {
                setJoinStatus(prev => ({ ...prev, [driveId]: { type: "success", text: `✅ Registered for ${data.company}!` } }));
                setRegisteredIds(prev => [...prev, driveId]);
                setCodeInputs(prev => ({ ...prev, [driveId]: "" }));
            } else {
                setJoinStatus(prev => ({ ...prev, [driveId]: { type: "error", text: data.error || "Registration failed." } }));
            }
        } finally {
            setJoining(null);
        }
    };

    const isEligible = (drive: Drive) => {
        if (!studentProfile) return null; // unknown
        const { grad_cgpa = 0, tenth_percent = 0, twelfth_percent = 0, active_backlogs = 99, branch = "" } = studentProfile;

        // If the user's branch is completely missing, explicitly prompt them to fill out their profile
        if (!branch || branch.trim() === "") return null;

        if (drive.min_cgpa > 0 && grad_cgpa < drive.min_cgpa) return false;
        if (drive.min_10th > 0 && tenth_percent < drive.min_10th) return false;
        if (drive.min_12th > 0 && twelfth_percent < drive.min_12th) return false;
        if (active_backlogs > drive.max_backlogs) return false;
        // Force branch into an array of strings just in case Supabase returns a Postgres string representation
        const branchesList = Array.isArray(drive.allowed_branches)
            ? drive.allowed_branches
            : typeof drive.allowed_branches === "string"
                ? [drive.allowed_branches]
                : [];

        if (branchesList.length > 0) {
            if (!branch || !branchesList.includes(branch)) {
                return false;
            }
        }
        return true;
    };

    if (loading) {
        return (
            <div className="flex flex-col items-center justify-center min-h-[500px] gap-3">
                <Loader2 className="w-10 h-10 animate-spin text-cyan-400" />
                <p className="text-sm font-medium text-slate-400 animate-pulse">Scanning placement network...</p>
            </div>
        );
    }

    return (
        <div className="space-y-8 max-w-6xl mx-auto pb-12">
            {/* Header Section */}
            <div className="relative rounded-3xl p-8 overflow-hidden border border-white/10 bg-gradient-to-r from-slate-900/90 via-slate-900/60 to-cyan-950/40 backdrop-blur-2xl shadow-2xl">
                <div className="absolute top-0 right-0 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl -z-10 pointer-events-none" />
                <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
                    <div>
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-semibold tracking-wider uppercase mb-3">
                            <Sparkles className="w-3.5 h-3.5" /> Direct Industry Portal
                        </div>
                        <h1 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight font-sora">
                            Placement <span className="bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 via-blue-400 to-indigo-400">Drives & Roles</span>
                        </h1>
                        <p className="text-slate-400 mt-2 max-w-xl text-sm leading-relaxed">
                            {drives.length} active placement opportunity{drives.length !== 1 ? "s" : ""} available. Enter your unique invitation code to unlock candidate registration.
                        </p>
                    </div>
                    <div className="flex items-center gap-3 bg-white/5 border border-white/10 p-3.5 rounded-2xl backdrop-blur-md">
                        <ShieldCheck className="w-8 h-8 text-cyan-400 shrink-0" />
                        <div>
                            <p className="text-xs text-slate-400">Real-time Matcher</p>
                            <p className="text-xs font-bold text-white">Profile Verified</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Drives List */}
            {drives.length === 0 ? (
                <div className="glass-card text-center py-24 px-6 space-y-4 rounded-3xl border border-white/10">
                    <Building2 className="w-16 h-16 text-slate-600 opacity-40 mx-auto" />
                    <h3 className="text-xl font-bold text-slate-300">No Placement Drives Active</h3>
                    <p className="text-sm text-slate-400 max-w-md mx-auto">Check back shortly. TPO and HR representatives post new campus hiring drives regularly.</p>
                </div>
            ) : (
                <div className="flex flex-col gap-6">
                    {drives.map((drive, i) => {
                        const eligible = isEligible(drive);
                        const registered = registeredIds.includes(drive.id);
                        const js = joinStatus[drive.id];

                        return (
                            <motion.div
                                key={drive.id}
                                initial={{ opacity: 0, y: 16 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: i * 0.07 }}
                                className={`group relative rounded-3xl border p-6 transition-all duration-300 backdrop-blur-xl ${
                                    registered
                                        ? "bg-emerald-950/20 border-emerald-500/40 shadow-[0_0_30px_rgba(16,185,129,0.1)]"
                                        : eligible === false
                                            ? "bg-slate-900/40 border-white/5 opacity-75 hover:opacity-100"
                                            : "bg-slate-900/80 border-white/10 hover:border-cyan-500/40 hover:shadow-[0_0_30px_rgba(56,189,248,0.15)]"
                                }`}
                            >
                                <div className="flex flex-col lg:flex-row gap-6">
                                    {/* Drive Info */}
                                    <div className="flex-1 space-y-5">
                                        <div className="flex items-start justify-between gap-4">
                                            <div className="flex items-center gap-4">
                                                <div className="w-14 h-14 bg-gradient-to-br from-slate-800 to-slate-900 border border-white/10 rounded-2xl flex items-center justify-center shrink-0 shadow-lg group-hover:scale-105 transition-transform duration-300">
                                                    <Building2 className="w-7 h-7 text-cyan-400" />
                                                </div>
                                                <div>
                                                    <div className="flex items-center gap-2.5 flex-wrap">
                                                        <h3 className="text-xl font-bold text-white font-sora tracking-wide">{drive.company}</h3>
                                                        {drive.source === "hr" ? (
                                                            <span className="px-2.5 py-0.5 bg-orange-500/10 text-orange-400 text-[10px] font-bold rounded-full border border-orange-500/30 uppercase tracking-wider shadow-sm">
                                                                Direct Corporate Role
                                                            </span>
                                                        ) : (
                                                            <span className="px-2.5 py-0.5 bg-cyan-500/10 text-cyan-400 text-[10px] font-bold rounded-full border border-cyan-500/30 uppercase tracking-wider shadow-sm">
                                                                Campus Drive
                                                            </span>
                                                        )}
                                                    </div>
                                                    {drive.target_roles && (
                                                        <p className="text-sm font-medium text-slate-300 mt-1">{drive.target_roles}</p>
                                                    )}
                                                </div>
                                            </div>

                                            {/* Status Badge */}
                                            <div className="shrink-0">
                                                {registered ? (
                                                    <span className="flex items-center gap-1.5 px-3.5 py-1.5 bg-emerald-500/10 text-emerald-400 text-xs font-bold rounded-xl border border-emerald-500/30 shadow-[0_0_15px_rgba(16,185,129,0.2)]">
                                                        <BadgeCheck className="w-4 h-4" /> Enrolled
                                                    </span>
                                                ) : eligible === false ? (
                                                    <span className="flex items-center gap-1.5 px-3.5 py-1.5 bg-rose-500/10 text-rose-400 text-xs font-bold rounded-xl border border-rose-500/30">
                                                        <AlertCircle className="w-4 h-4" /> Ineligible
                                                    </span>
                                                ) : eligible === true ? (
                                                    <span className="flex items-center gap-1.5 px-3.5 py-1.5 bg-emerald-500/10 text-emerald-400 text-xs font-bold rounded-xl border border-emerald-500/30">
                                                        <CheckCircle2 className="w-4 h-4" /> Eligible
                                                    </span>
                                                ) : (
                                                    <span className="px-3.5 py-1.5 bg-amber-500/10 text-amber-400 text-xs font-bold rounded-xl border border-amber-500/30">
                                                        Complete Profile
                                                    </span>
                                                )}
                                            </div>
                                        </div>

                                        {/* Drive Meta Pills */}
                                        <div className="flex flex-wrap gap-4 text-xs font-medium text-slate-400">
                                            <div className="flex items-center gap-2 bg-white/5 border border-white/5 px-3 py-1.5 rounded-xl">
                                                <Calendar className="w-3.5 h-3.5 text-cyan-400" />
                                                <span>{new Date(drive.drive_date).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}</span>
                                            </div>
                                            <div className="flex items-center gap-2 bg-white/5 border border-white/5 px-3 py-1.5 rounded-xl">
                                                <Users className="w-3.5 h-3.5 text-indigo-400" />
                                                <span>{drive.enrolled_count} / {drive.expected_intake > 0 ? `${drive.expected_intake} Intake` : 'Unlimited'}</span>
                                            </div>
                                            {drive.location && (
                                                <div className="flex items-center gap-2 bg-white/5 border border-white/5 px-3 py-1.5 rounded-xl">
                                                    <MapPin className="w-3.5 h-3.5 text-purple-400" />
                                                    <span>{drive.location}</span>
                                                </div>
                                            )}
                                        </div>

                                        {/* Eligibility Criteria Badges */}
                                        <div className="flex flex-wrap gap-2 pt-1">
                                            {drive.min_cgpa > 0 && (
                                                <span className={`px-3 py-1 text-xs font-bold rounded-xl border transition-colors ${
                                                    studentProfile && studentProfile.grad_cgpa >= drive.min_cgpa 
                                                        ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" 
                                                        : "bg-purple-500/10 text-purple-400 border-purple-500/20"
                                                }`}>
                                                    Min CGPA: {drive.min_cgpa}
                                                </span>
                                            )}
                                            {drive.min_10th > 0 && (
                                                <span className={`px-3 py-1 text-xs font-bold rounded-xl border transition-colors ${
                                                    studentProfile && studentProfile.tenth_percent >= drive.min_10th 
                                                        ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" 
                                                        : "bg-cyan-500/10 text-cyan-400 border-cyan-500/20"
                                                }`}>
                                                    10th ≥ {drive.min_10th}%
                                                </span>
                                            )}
                                            {drive.min_12th > 0 && (
                                                <span className={`px-3 py-1 text-xs font-bold rounded-xl border transition-colors ${
                                                    studentProfile && studentProfile.twelfth_percent >= drive.min_12th 
                                                        ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" 
                                                        : "bg-cyan-500/10 text-cyan-400 border-cyan-500/20"
                                                }`}>
                                                    12th ≥ {drive.min_12th}%
                                                </span>
                                            )}
                                            {drive.max_backlogs === 0 && (
                                                <span className="px-3 py-1 text-xs font-bold rounded-xl border bg-rose-500/10 text-rose-400 border-rose-500/20">
                                                    0 Active Backlogs
                                                </span>
                                            )}
                                            {drive.allowed_branches?.length > 0 && (
                                                <span className="px-3 py-1 text-xs font-bold rounded-xl border bg-white/5 text-slate-300 border-white/10 flex items-center gap-1.5">
                                                    <GraduationCap className="w-3.5 h-3.5 text-cyan-400" />
                                                    {drive.allowed_branches.join(", ")}
                                                </span>
                                            )}
                                        </div>
                                    </div>

                                    {/* Action Box */}
                                    <div className="lg:w-72 shrink-0 flex flex-col justify-center border-t lg:border-t-0 lg:border-l border-white/10 pt-5 lg:pt-0 lg:pl-6 space-y-3">
                                        {registered ? (
                                            <div className="flex flex-col items-center justify-center p-5 bg-gradient-to-br from-emerald-950/40 to-slate-900 border border-emerald-500/30 rounded-2xl text-center space-y-2">
                                                <div className="w-10 h-10 rounded-full bg-emerald-500/20 flex items-center justify-center text-emerald-400">
                                                    <BadgeCheck className="w-6 h-6" />
                                                </div>
                                                <p className="text-sm font-bold text-emerald-400">Successfully Registered!</p>
                                                <p className="text-xs text-slate-400">Your profile metrics have been locked for HR review.</p>
                                            </div>
                                        ) : (
                                            <>
                                                <div className="relative">
                                                    <KeyRound className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                                    <input
                                                        className="w-full bg-slate-950/80 border border-white/10 rounded-xl pl-10 pr-4 py-3 outline-none focus:border-cyan-400 focus:shadow-[0_0_15px_rgba(56,189,248,0.2)] transition-all font-mono text-sm tracking-widest uppercase text-white placeholder:text-slate-600 placeholder:font-sans placeholder:tracking-normal"
                                                        placeholder="Enter Access Code"
                                                        value={codeInputs[drive.id] || ""}
                                                        onChange={e => setCodeInputs(prev => ({ ...prev, [drive.id]: e.target.value }))}
                                                        onKeyDown={e => e.key === "Enter" && handleJoin(drive.id, drive.drive_code)}
                                                    />
                                                </div>
                                                <button
                                                    onClick={() => handleJoin(drive.id, drive.drive_code)}
                                                    disabled={joining === drive.id}
                                                    className="w-full bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 font-bold py-3 rounded-xl transition-all shadow-[0_0_20px_rgba(56,189,248,0.3)] hover:shadow-[0_0_30px_rgba(56,189,248,0.5)] disabled:opacity-50 flex items-center justify-center gap-2 text-sm"
                                                >
                                                    {joining === drive.id ? (
                                                        <Loader2 className="w-4 h-4 animate-spin text-slate-950" />
                                                    ) : (
                                                        <>
                                                            <Lock className="w-4 h-4" />
                                                            Register for Drive
                                                            <ArrowRight className="w-4 h-4" />
                                                        </>
                                                    )}
                                                </button>

                                                <AnimatePresence>
                                                    {js && (
                                                        <motion.p
                                                            initial={{ opacity: 0, y: 4 }}
                                                            animate={{ opacity: 1, y: 0 }}
                                                            exit={{ opacity: 0 }}
                                                            className={`text-xs px-3.5 py-2.5 rounded-xl border text-center font-medium ${
                                                                js.type === "success"
                                                                    ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                                                                    : "bg-rose-500/10 text-rose-400 border-rose-500/20"
                                                            }`}
                                                        >
                                                            {js.text}
                                                        </motion.p>
                                                    )}
                                                </AnimatePresence>
                                            </>
                                        )}
                                    </div>
                                </div>
                            </motion.div>
                        );
                    })}
                </div>
            )}
        </div>
    );
}

